# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
rm /etc/machine-id
systemd-machine-id-setup
sudo apt update -y
sudo apt install network-manager -y
sudo install openssh-server -y
sudo systemctl enable ssh 
sudo systemctl start ssh
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "mpasternak/focal64-arm"
  config.vm.box_check_update = false

    config.vm.define "master-1" do |node|
      node.vm.provider "parallels" do |vb|
          vb.name = "kubernetes-master-1"
          vb.memory = 2048
          vb.cpus = 2
      end
      node.vm.hostname = "master-1"
      node.vm.network :private_network, ip: "192.168.5.21"
      node.vm.network "forwarded_port", guest: 22, host: "2711"
      node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh"
      node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
      node.vm.provision "shell", inline: $script
    end

    config.vm.define "worker-1" do |node|
      node.vm.provider "parallels" do |vb|
          vb.name = "kubernetes-worker-1"
          vb.memory = 512
          vb.cpus = 1
      end
      node.vm.hostname = "worker-1"
      node.vm.network :private_network, ip: "192.168.5.11"
      node.vm.network "forwarded_port", guest: 22, host: "2721"
      node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh"
      node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
      node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker-2.sh"
      node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "ubuntu/allow-bridge-nf-traffic.sh"
      node.vm.provision "shell", inline: $script
      end

      config.vm.define "worker-2" do |node|
        node.vm.provider "parallels" do |vb|
            vb.name = "kubernetes-worker-2"
            vb.memory = 512
            vb.cpus = 1
        end
        node.vm.hostname = "worker-2"
        node.vm.network :private_network, ip: "192.168.5.12"
        node.vm.network "forwarded_port", guest: 22, host: "2722"
        node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh"
        node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
        node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker-2.sh"
        node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "ubuntu/allow-bridge-nf-traffic.sh"
        node.vm.provision "shell", inline: $script
        end


      config.vm.define "worker-3" do |node|
        node.vm.provider "parallels" do |vb|
            vb.name = "kubernetes-worker-3"
            vb.memory = 512
            vb.cpus = 1
        end
        node.vm.hostname = "worker-3"
        node.vm.network :private_network, ip: "192.168.5.13"
        node.vm.network "forwarded_port", guest: 22, host: "2723"
        node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh"
        node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
        node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker-2.sh"
        node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "ubuntu/allow-bridge-nf-traffic.sh"
        node.vm.provision "shell", inline: $script
        end


        config.vm.define "worker-4" do |node|
          node.vm.provider "parallels" do |vb|
              vb.name = "kubernetes-worker-4"
              vb.memory = 512
              vb.cpus = 1
          end
          node.vm.hostname = "worker-4"
          node.vm.network :private_network, ip: "192.168.5.14"
          node.vm.network "forwarded_port", guest: 22, host: "2724"
          node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh"
          node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
          node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker-2.sh"
          node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "ubuntu/allow-bridge-nf-traffic.sh"
          node.vm.provision "shell", inline: $script
          end
      
end     
